### ISSUE TITLE
Miniconda3 is not installing fully

### ISSUE THREAD

**Issue by SergioLordano** [oasys-kit/oasys-installation-scripts#10]
Dear Luca,

Firstly, thank's for the installations scripts getting always simpler! However, we are facing an issue in nearly all new installations, and maybe others are too. It's nothing wrong with the oasys installation scripts, but rather with miniconda. It is a well known issue from Anaconda that sometimes the installation is not full. And by that I mean that the `Miniconda/Scripts/activate.bat` is not present ater installation, along with many other stuff.

I found a workaround based on [this link](https://docs.anaconda.com/anaconda/user-guide/troubleshooting/#cannot-open-anaconda-prompt-after-installation). This solution can be adapted, installing miniconda as follows:
```
start /wait "" mc3.exe /InstallationType=JustMe /AddToPath=0 /RegisterPython=0 /NoRegistry=0 /S /D=%UserProfile%\Miniconda3
%UserProfile%\Miniconda3\Scripts\activate.bat
```
I guess it is also a good idea to activate the miniconda base env before installing the libraries in aux_bin. In my case, I have another Anaconda installation and it skipped some depencies installations that it could found on this other installation.

I am curious, nobody reported on that yet? I guess many people would just realize the problem when clicking the oasys icon, and then is asks for you to point the `activate.bat` file location. 
Well, thank you again!

**Comment by lucarebuffi** [comment]
Thank you for telling us: This is a first for me.  Be aware that our environment is not just a whatever Anaconda, but a specific version of Miniconda. We will work on that as soon as we have time.

**Comment by SergioLordano** [comment]
You are right, what solved for me was changing the version of miniconda, I did't realize that at first. Specifically, the `Miniconda3-py37_4.8.2-Windows-x86_64.exe` works here. Sorry about that, I guess you have a good reason to stick with that other version. 

Anyway, I think it is useful for you to know that sometimed miniconda does not install fully. Why and when it happens is a mistery for me.

Best regards, Sergio.

**Comment by lucarebuffi** [comment]
The reason is to avoid unpredictability, being sure that all the users have the same version, in which we tested the software. 

It was VERY useful, thank you again!

**Comment by lucarebuffi** [comment]
Changed the Miniconda version.
