### ISSUE TITLE
add-ons installation problem

### ISSUE THREAD

**Issue by trebushi** [oasys-kit/oasys-installation-scripts#11]
Dear developer, 

Could you suggest what can be wrong with the add-ons installation (see a screenshot in the attachment)?
I am using Linux Mint 20, on 19.3 it worked perfectly.

Best wishes, 
Andrei Trebushinin

![Screenshot from 2020-07-21 14-57-23](https://user-images.githubusercontent.com/23503374/88028748-42bb6680-cb63-11ea-8d13-a700f926b160.png)

**Comment by lucarebuffi** [comment]
Dear User, please Copy/Paste the message that is in the Error Pop-up, and maybe I could give you an answer.

**Comment by trebushi** [comment]
Dear Luca,

Is seems, I solved my problem just by installing some essential packets on linux and also for python. Sorry, for bothering. 

The problem looked like this...

Processing
/home/tae/.cache/pip/wheels/c5/5a/7a/2a4bdc740e92258df241a4bf5adfd90d7a7e4eade0b2aedb2f/OASYS1_ShadowOui_Advanced_Tools-1.0.13-py3-none-any.whl

Collecting oasys-srwpy>=1.0.3

Using cached oasys-srwpy-1.0.3.tar.gz (4.3 MB)

Requirement already satisfied: oasys1>=1.2.43 in
/home/tae/miniconda3/lib/python3.7/site-packages (from
OASYS1-ShadowOui-Advanced-Tools) (1.2.44)

Collecting scikit-image

Using cached scikit_image-0.17.2-cp37-cp37m-manylinux1_x86_64.whl (12.5 MB)

Requirement already satisfied: OASYS1-ShadowOui>=1.5.83 in
/home/tae/miniconda3/lib/python3.7/site-packages (from
OASYS1-ShadowOui-Advanced-Tools) (1.5.84)

Requirement already satisfied: setuptools in
/home/tae/miniconda3/lib/python3.7/site-packages (from
OASYS1-ShadowOui-Advanced-Tools) (41.4.0)

Requirement already satisfied: matplotlib in
/home/tae/miniconda3/lib/python3.7/site-packages (from
oasys-srwpy>=1.0.3->OASYS1-ShadowOui-Advanced-Tools) (3.3.0)

Requirement already satisfied: numpy in
/home/tae/miniconda3/lib/python3.7/site-packages (from
oasys-srwpy>=1.0.3->OASYS1-ShadowOui-Advanced-Tools) (1.19.1)

Requirement already satisfied: pillow in
/home/tae/miniconda3/lib/python3.7/site-packages (from
oasys-srwpy>=1.0.3->OASYS1-ShadowOui-Advanced-Tools) (7.2.0)

Requirement already satisfied: scipy in
/home/tae/miniconda3/lib/python3.7/site-packages (from
oasys-srwpy>=1.0.3->OASYS1-ShadowOui-Advanced-Tools) (1.5.1)

Requirement already satisfied: oasys-canvas-core>=1.0.6 in
/home/tae/miniconda3/lib/python3.7/site-packages (from
oasys1>=1.2.43->OASYS1-ShadowOui-Advanced-Tools) (1.0.6)

Requirement already satisfied: srxraylib>=1.0.28 in
/home/tae/miniconda3/lib/python3.7/site-packages (from
oasys1>=1.2.43->OASYS1-ShadowOui-Advanced-Tools) (1.0.29)

Requirement already satisfied: oasys-widget-core>=1.0.0 in
/home/tae/miniconda3/lib/python3.7/site-packages (from
oasys1>=1.2.43->OASYS1-ShadowOui-Advanced-Tools) (1.0.0)

Requirement already satisfied: syned>=1.0.16 in
/home/tae/miniconda3/lib/python3.7/site-packages (from
oasys1>=1.2.43->OASYS1-ShadowOui-Advanced-Tools) (1.0.16)

Requirement already satisfied: hdf5plugin in
/home/tae/miniconda3/lib/python3.7/site-packages (from
oasys1>=1.2.43->OASYS1-ShadowOui-Advanced-Tools) (2.3.0)

Requirement already satisfied: wofry>=1.0.22 in
/home/tae/miniconda3/lib/python3.7/site-packages (from
oasys1>=1.2.43->OASYS1-ShadowOui-Advanced-Tools) (1.0.23)

Requirement already satisfied: silx>=0.11.0 in
/home/tae/miniconda3/lib/python3.7/site-packages (from
oasys1>=1.2.43->OASYS1-ShadowOui-Advanced-Tools) (0.13.1)

Requirement already satisfied: PyQt5>=5.14 in
/home/tae/miniconda3/lib/python3.7/site-packages (from
oasys1>=1.2.43->OASYS1-ShadowOui-Advanced-Tools) (5.15.0)

Requirement already satisfied: requests in
/home/tae/miniconda3/lib/python3.7/site-packages (from
oasys1>=1.2.43->OASYS1-ShadowOui-Advanced-Tools) (2.22.0)

Collecting networkx>=2.0

Using cached networkx-2.4-py3-none-any.whl (1.6 MB)

Collecting tifffile>=2019.7.26

Downloading tifffile-2020.7.22-py3-none-any.whl (145 kB)

Collecting PyWavelets>=1.1.1

Using cached PyWavelets-1.1.1-cp37-cp37m-manylinux1_x86_64.whl (4.4 MB)

Collecting imageio>=2.3.0

Using cached imageio-2.9.0-py3-none-any.whl (3.3 MB)

Requirement already satisfied: shadow3>=18.5.30 in
/home/tae/miniconda3/lib/python3.7/site-packages (from
OASYS1-ShadowOui>=1.5.83->OASYS1-ShadowOui-Advanced-Tools) (18.5.30)

Requirement already satisfied: wofryshadow>=1.0.3 in
/home/tae/miniconda3/lib/python3.7/site-packages (from
OASYS1-ShadowOui>=1.5.83->OASYS1-ShadowOui-Advanced-Tools) (1.0.3)

Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in
/home/tae/miniconda3/lib/python3.7/site-packages (from
matplotlib->oasys-srwpy>=1.0.3->OASYS1-ShadowOui-Advanced-Tools) (2.4.7)

Requirement already satisfied: kiwisolver>=1.0.1 in
/home/tae/miniconda3/lib/python3.7/site-packages (from
matplotlib->oasys-srwpy>=1.0.3->OASYS1-ShadowOui-Advanced-Tools) (1.2.0)

Requirement already satisfied: cycler>=0.10 in
/home/tae/miniconda3/lib/python3.7/site-packages (from
matplotlib->oasys-srwpy>=1.0.3->OASYS1-ShadowOui-Advanced-Tools) (0.10.0)

Requirement already satisfied: python-dateutil>=2.1 in
/home/tae/miniconda3/lib/python3.7/site-packages (from
matplotlib->oasys-srwpy>=1.0.3->OASYS1-ShadowOui-Advanced-Tools) (2.8.1)

Requirement already satisfied: six in
/home/tae/miniconda3/lib/python3.7/site-packages (from
oasys-canvas-core>=1.0.6->oasys1>=1.2.43->OASYS1-ShadowOui-Advanced-Tools)
(1.12.0)

Requirement already satisfied: h5py in
/home/tae/miniconda3/lib/python3.7/site-packages (from
hdf5plugin->oasys1>=1.2.43->OASYS1-ShadowOui-Advanced-Tools) (2.10.0)

Requirement already satisfied: fabio>=0.9 in
/home/tae/miniconda3/lib/python3.7/site-packages (from
silx>=0.11.0->oasys1>=1.2.43->OASYS1-ShadowOui-Advanced-Tools) (0.10.2)

Requirement already satisfied: PyQt5-sip<13,>=12.8 in
/home/tae/miniconda3/lib/python3.7/site-packages (from
PyQt5>=5.14->oasys1>=1.2.43->OASYS1-ShadowOui-Advanced-Tools) (12.8.0)

Requirement already satisfied: idna<2.9,>=2.5 in
/home/tae/miniconda3/lib/python3.7/site-packages (from
requests->oasys1>=1.2.43->OASYS1-ShadowOui-Advanced-Tools) (2.8)

Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in
/home/tae/miniconda3/lib/python3.7/site-packages (from
requests->oasys1>=1.2.43->OASYS1-ShadowOui-Advanced-Tools) (1.24.2)

Requirement already satisfied: certifi>=2017.4.17 in
/home/tae/miniconda3/lib/python3.7/site-packages (from
requests->oasys1>=1.2.43->OASYS1-ShadowOui-Advanced-Tools) (2019.9.11)

Requirement already satisfied: chardet<3.1.0,>=3.0.2 in
/home/tae/miniconda3/lib/python3.7/site-packages (from
requests->oasys1>=1.2.43->OASYS1-ShadowOui-Advanced-Tools) (3.0.4)

Collecting decorator>=4.3.0

Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)

Building wheels for collected packages: oasys-srwpy

Building wheel for oasys-srwpy (setup.py): started

Building wheel for oasys-srwpy (setup.py): finished with status 'error'

ERROR: Command errored out with exit status 1:

command: /home/tae/miniconda3/bin/python -u -c 'import sys, setuptools,
tokenize; sys.argv[0] =
'"'"'/tmp/pip-install-thl2jbjt/oasys-srwpy/setup.py'"'"';
__file__='"'"'/tmp/pip-install-thl2jbjt/oasys-srwpy/setup.py'"'"';f=getattr(tokenize,
'"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"',
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
bdist_wheel -d /tmp/pip-wheel-dtfnlxve

cwd: /tmp/pip-install-thl2jbjt/oasys-srwpy/

Complete output (67 lines):

running bdist_wheel

running build

make: Entering directory '/tmp/pip-install-thl2jbjt/oasys-srwpy/core'

rm -f /tmp/pip-install-thl2jbjt/oasys-srwpy/core/gcc/libfftw.a
/tmp/pip-install-thl2jbjt/oasys-srwpy/core/gcc/libsrw.a && \

rm -rf /tmp/pip-install-thl2jbjt/oasys-srwpy/core/fftw-2.1.5/

git clone https://github.com/oasys-kit/FFTW.git fftw-2.1.5 && \

cd fftw-2.1.5 && \

CFLAGS=-fPIC ./configure --enable-float --with-pic && \

make -j8 && \

cp fftw/.libs/libfftw.a /tmp/pip-install-thl2jbjt/oasys-srwpy/core/gcc && \

cd /tmp/pip-install-thl2jbjt/oasys-srwpy/core && \

rm -rf fftw-2.1.5;

Cloning into 'fftw-2.1.5'...

checking for a BSD-compatible install... /usr/bin/install -c

checking whether build environment is sane... yes

checking for gawk... gawk

checking whether make sets $(MAKE)... yes

checking type prefix for installed files... (none)

checking for vendor's cc to be used instead of gcc... checking for cc... cc

checking for C compiler default output... configure: error: C compiler
cannot create executables

See `config.log' for more details.

make: *** [Makefile:13: fftw] Error 77

make: Leaving directory '/tmp/pip-install-thl2jbjt/oasys-srwpy/core'

running build_py

creating build

creating build/lib.linux-x86_64-3.7

creating build/lib.linux-x86_64-3.7/oasys_srw

copying oasys_srw/uti_plot_com.py -> build/lib.linux-x86_64-3.7/oasys_srw

copying oasys_srw/__init__.py -> build/lib.linux-x86_64-3.7/oasys_srw

copying oasys_srw/srwl_uti_src.py -> build/lib.linux-x86_64-3.7/oasys_srw

copying oasys_srw/srwl_uti_mag.py -> build/lib.linux-x86_64-3.7/oasys_srw

copying oasys_srw/srwl_bl.py -> build/lib.linux-x86_64-3.7/oasys_srw

copying oasys_srw/uti_parse.py -> build/lib.linux-x86_64-3.7/oasys_srw

copying oasys_srw/srwl_uti_und.py -> build/lib.linux-x86_64-3.7/oasys_srw

copying oasys_srw/srwl_uti_smp.py -> build/lib.linux-x86_64-3.7/oasys_srw

copying oasys_srw/srwl_uti_cryst.py -> build/lib.linux-x86_64-3.7/oasys_srw

copying oasys_srw/srwlib.py -> build/lib.linux-x86_64-3.7/oasys_srw

copying oasys_srw/uti_math.py -> build/lib.linux-x86_64-3.7/oasys_srw

copying oasys_srw/uti_io.py -> build/lib.linux-x86_64-3.7/oasys_srw

copying oasys_srw/uti_plot.py -> build/lib.linux-x86_64-3.7/oasys_srw

copying oasys_srw/uti_plot_matplotlib.py ->
build/lib.linux-x86_64-3.7/oasys_srw

copying oasys_srw/SRWLIB_ExampleViewDataFile.py ->
build/lib.linux-x86_64-3.7/oasys_srw

creating build/lib.linux-x86_64-3.7/oasys_srw/tests

copying oasys_srw/tests/__init__.py ->
build/lib.linux-x86_64-3.7/oasys_srw/tests

copying oasys_srw/tests/conftest.py ->
build/lib.linux-x86_64-3.7/oasys_srw/tests

copying oasys_srw/tests/test_examples.py ->
build/lib.linux-x86_64-3.7/oasys_srw/tests

running egg_info

writing oasys_srwpy.egg-info/PKG-INFO

writing dependency_links to oasys_srwpy.egg-info/dependency_links.txt

writing requirements to oasys_srwpy.egg-info/requires.txt

writing top-level names to oasys_srwpy.egg-info/top_level.txt

reading manifest file 'oasys_srwpy.egg-info/SOURCES.txt'

reading manifest template 'MANIFEST.in'

warning: no previously-included files matching '__pycache__' found under
directory '*'

warning: no previously-included files matching '*.py[co]' found under
directory '*'

writing manifest file 'oasys_srwpy.egg-info/SOURCES.txt'

running build_ext

building 'srwlpy' extension

creating build/temp.linux-x86_64-3.7

creating build/temp.linux-x86_64-3.7/core

creating build/temp.linux-x86_64-3.7/core/src

creating build/temp.linux-x86_64-3.7/core/src/clients

creating build/temp.linux-x86_64-3.7/core/src/clients/python

gcc -pthread -B /home/tae/miniconda3/compiler_compat -Wl,--sysroot=/
-Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC
-Icore/src/lib -I/home/tae/miniconda3/include/python3.7m -c
core/src/clients/python/srwlpy.cpp -o
build/temp.linux-x86_64-3.7/core/src/clients/python/srwlpy.o

gcc: fatal error: cannot execute ‘cc1plus’: execvp: No such file or
directory

compilation terminated.

error: command 'gcc' failed with exit status 1

----------------------------------------

ERROR: Failed building wheel for oasys-srwpy

Running setup.py clean for oasys-srwpy

Failed to build oasys-srwpy

Installing collected packages: oasys-srwpy, decorator, networkx, tifffile,
PyWavelets, imageio, scikit-image, OASYS1-ShadowOui-Advanced-Tools

Running setup.py install for oasys-srwpy: started

Running setup.py install for oasys-srwpy: finished with status 'error'

ERROR: Command errored out with exit status 1:

command: /home/tae/miniconda3/bin/python -u -c 'import sys, setuptools,
tokenize; sys.argv[0] =
'"'"'/tmp/pip-install-thl2jbjt/oasys-srwpy/setup.py'"'"';
__file__='"'"'/tmp/pip-install-thl2jbjt/oasys-srwpy/setup.py'"'"';f=getattr(tokenize,
'"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"',
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
install --record /tmp/pip-record-_0gfu2se/install-record.txt
--single-version-externally-managed --compile --install-headers
/home/tae/miniconda3/include/python3.7m/oasys-srwpy

cwd: /tmp/pip-install-thl2jbjt/oasys-srwpy/

Complete output (67 lines):

running install

running build

make: Entering directory '/tmp/pip-install-thl2jbjt/oasys-srwpy/core'

rm -f /tmp/pip-install-thl2jbjt/oasys-srwpy/core/gcc/libfftw.a
/tmp/pip-install-thl2jbjt/oasys-srwpy/core/gcc/libsrw.a && \

rm -rf /tmp/pip-install-thl2jbjt/oasys-srwpy/core/fftw-2.1.5/

git clone https://github.com/oasys-kit/FFTW.git fftw-2.1.5 && \

cd fftw-2.1.5 && \

CFLAGS=-fPIC ./configure --enable-float --with-pic && \

make -j8 && \

cp fftw/.libs/libfftw.a /tmp/pip-install-thl2jbjt/oasys-srwpy/core/gcc && \

cd /tmp/pip-install-thl2jbjt/oasys-srwpy/core && \

rm -rf fftw-2.1.5;

Cloning into 'fftw-2.1.5'...

checking for a BSD-compatible install... /usr/bin/install -c

checking whether build environment is sane... yes

checking for gawk... gawk

checking whether make sets $(MAKE)... yes

checking type prefix for installed files... (none)

checking for vendor's cc to be used instead of gcc... checking for cc... cc

checking for C compiler default output... configure: error: C compiler
cannot create executables

See `config.log' for more details.

make: *** [Makefile:13: fftw] Error 77

make: Leaving directory '/tmp/pip-install-thl2jbjt/oasys-srwpy/core'

running build_py

creating build

creating build/lib.linux-x86_64-3.7

creating build/lib.linux-x86_64-3.7/oasys_srw

copying oasys_srw/uti_plot_com.py -> build/lib.linux-x86_64-3.7/oasys_srw

copying oasys_srw/__init__.py -> build/lib.linux-x86_64-3.7/oasys_srw

copying oasys_srw/srwl_uti_src.py -> build/lib.linux-x86_64-3.7/oasys_srw

copying oasys_srw/srwl_uti_mag.py -> build/lib.linux-x86_64-3.7/oasys_srw

copying oasys_srw/srwl_bl.py -> build/lib.linux-x86_64-3.7/oasys_srw

copying oasys_srw/uti_parse.py -> build/lib.linux-x86_64-3.7/oasys_srw

copying oasys_srw/srwl_uti_und.py -> build/lib.linux-x86_64-3.7/oasys_srw

copying oasys_srw/srwl_uti_smp.py -> build/lib.linux-x86_64-3.7/oasys_srw

copying oasys_srw/srwl_uti_cryst.py -> build/lib.linux-x86_64-3.7/oasys_srw

copying oasys_srw/srwlib.py -> build/lib.linux-x86_64-3.7/oasys_srw

copying oasys_srw/uti_math.py -> build/lib.linux-x86_64-3.7/oasys_srw

copying oasys_srw/uti_io.py -> build/lib.linux-x86_64-3.7/oasys_srw

copying oasys_srw/uti_plot.py -> build/lib.linux-x86_64-3.7/oasys_srw

copying oasys_srw/uti_plot_matplotlib.py ->
build/lib.linux-x86_64-3.7/oasys_srw

copying oasys_srw/SRWLIB_ExampleViewDataFile.py ->
build/lib.linux-x86_64-3.7/oasys_srw

creating build/lib.linux-x86_64-3.7/oasys_srw/tests

copying oasys_srw/tests/__init__.py ->
build/lib.linux-x86_64-3.7/oasys_srw/tests

copying oasys_srw/tests/conftest.py ->
build/lib.linux-x86_64-3.7/oasys_srw/tests

copying oasys_srw/tests/test_examples.py ->
build/lib.linux-x86_64-3.7/oasys_srw/tests

running egg_info

writing oasys_srwpy.egg-info/PKG-INFO

writing dependency_links to oasys_srwpy.egg-info/dependency_links.txt

writing requirements to oasys_srwpy.egg-info/requires.txt

writing top-level names to oasys_srwpy.egg-info/top_level.txt

reading manifest file 'oasys_srwpy.egg-info/SOURCES.txt'

reading manifest template 'MANIFEST.in'

warning: no previously-included files matching '__pycache__' found under
directory '*'

warning: no previously-included files matching '*.py[co]' found under
directory '*'

writing manifest file 'oasys_srwpy.egg-info/SOURCES.txt'

running build_ext

building 'srwlpy' extension

creating build/temp.linux-x86_64-3.7

creating build/temp.linux-x86_64-3.7/core

creating build/temp.linux-x86_64-3.7/core/src

creating build/temp.linux-x86_64-3.7/core/src/clients

creating build/temp.linux-x86_64-3.7/core/src/clients/python

gcc -pthread -B /home/tae/miniconda3/compiler_compat -Wl,--sysroot=/
-Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC
-Icore/src/lib -I/home/tae/miniconda3/include/python3.7m -c
core/src/clients/python/srwlpy.cpp -o
build/temp.linux-x86_64-3.7/core/src/clients/python/srwlpy.o

gcc: fatal error: cannot execute ‘cc1plus’: execvp: No such file or
directory

compilation terminated.

error: command 'gcc' failed with exit status 1

----------------------------------------

ERROR: Command errored out with exit status 1:
/home/tae/miniconda3/bin/python -u -c 'import sys, setuptools, tokenize;
sys.argv[0] = '"'"'/tmp/pip-install-thl2jbjt/oasys-srwpy/setup.py'"'"';
__file__='"'"'/tmp/pip-install-thl2jbjt/oasys-srwpy/setup.py'"'"';f=getattr(tokenize,
'"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"',
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
install --record /tmp/pip-record-_0gfu2se/install-record.txt
--single-version-externally-managed --compile --install-headers
/home/tae/miniconda3/include/python3.7m/oasys-srwpy Check the logs for full
command output.

**Comment by lucarebuffi** [comment]
Dear Andrei, the installation failed because it tried to compile SRW core library but there are issues with the compiler:

checking for C compiler default output... configure: error: C compiler
cannot create executables

See `config.log' for more details.

make: *** [Makefile:13: fftw] Error 77


gcc: fatal error: cannot execute ‘cc1plus’: execvp: No such file or
directory

**Comment by lucarebuffi** [comment]
try install the package gcc-c++

`sudo apt-get install g++`

**Comment by lucarebuffi** [comment]
It could be beneficial to install gfortran-7, but only if ShadowOui fails to. install.

`sudo apt install gfortran-7`

**Comment by trebushi** [comment]
Dear Luca,

Yes, I did this. I totally forgot about C compilers needed fo SRW.
Everything works fine now. Thank you a lot!

Best regards,
Andrei
