### ISSUE TITLE
applet windows 

### ISSUE THREAD

**Issue by trebushi** [oasys-kit/oasys-installation-scripts#12]
Dear Authors, 

Some of the lines for parameters in the applet windows are not displayed correctly on my machine, for example in the screenshot the line "Ruling Density at origin [Lines .... " (please, find the screenshot in the attachment).
![Screenshot from 2020-08-16 18-30-29](https://user-images.githubusercontent.com/23503374/90333391-8f258500-dfef-11ea-8201-5fd63e19d5c3.png)

It seems I cannot rescale the windows. I am using Linux Mint 20.

Thanks in advance,
Andrei

**Comment by lucarebuffi** [comment]
Please carefully read the instruction about high DPI monitors. See at the end of:

https://github.com/oasys-kit/oasys-installation-scripts/wiki/Install-Oasys-in-Windows-10

**Comment by TrebAndrew** [comment]
Dear Luca,

How can I do it on Linux Mint?

**Comment by lucarebuffi** [comment]
dear Andrei, I deleted my previous comment because it was OT. Oasys renders the forms by using PyQt, that is using the native environment. I optimize the aspect in a Mac, please see how the same page looks on that environment.

![Screen Shot 2020-08-18 at 10 54 53 AM](https://user-images.githubusercontent.com/6713598/90536120-42ea5a00-e141-11ea-802f-239e39e0b5e7.png)

**Comment by lucarebuffi** [comment]
From what I see you have a very poor resolution, so the form appears like "compressed". In windows we also find that PyQt struggles with High DPI resolution, with fractional pixel size. In Windows you can set the program to ignore the High DPI setting. I also tried to disable it at the python level but I was unsuccessful in Windows. Maybe it works in Linux.

Could you please tell me if you have High DPI enabled? (in the preferences, go to the hardware section and then Display)
If so could you try to disable it and see how OASYS looks like?

Thanks

**Comment by lucarebuffi** [comment]
I installed a Mint 20 virtual environment and I see no issues. Please check your display resolution.

![Screen Shot 2020-08-18 at 11 51 43 AM](https://user-images.githubusercontent.com/6713598/90542194-5994af00-e149-11ea-9cd2-83f32e34fc1d.png)

**Comment by trebushi** [comment]
Dear Luca,

Thank you for your recommendations. I adjusted the font size on my computer
to a minimum size I can work with and it solved the problem of "Ruling
Density at..." and it works for most of the other titles too. Sorry if my
request was that simple to solve. But I have some minor questions about the
plotting routine that have seemingly the same problem. Please, look at a
screenshot in the attachment. Is there a way no to cut off the axes titles
of the figures, which are in most of the applets? Is it a common
appearance? I saw the same problem with the plots from my colleagues.

Regarding your last letter, I have two monitors 1920x1080 and 2560x1440,
OASYS windows appear similarly on both of them. The hi-DPI option is always
disabled on my computer. But I checked what happens if it is enabled...

Best wishes,
Andrei

**Comment by lucarebuffi** [comment]
Dear Andrei, there is no attachment I can see. Anyway, plots are made with the silx library (https://github.com/silx-kit/silx) and 'matplotlib' backend. I have no control on the rendering so far. Better plots are always with the plotXY widget, where you can export the plot in hdf5 format, so you can, in case, plot it with an external tool. This is what we do when we need to have nice figures for papers and presentations.
