### ISSUE TITLE
Cannot update internal libraries or update add-ons (OS X)

### ISSUE THREAD

**Issue by amicitas** [oasys-kit/oasys-installation-scripts#13]
I am having an issue that everytime that I start OASYS I get a popup diaglog:

    OASYS needs to update its internal libraries.
    (Strongly recommended to avoid malfunctioning)

    The application will close automatically.
    Confirm?

If I click yes OASYS will ask if I want to update addons, and then shut down When I restart I get the same popup again.  I have tried reinstalling, but the same issue appears.

I am also unable to update addons.  I get a notification, and am able to start the upgrade process, but after restarting OASYS the addon is still at the previous version.  Currently I have the issue with the `ShadowOui` addon.  I don't know if this issue is a related issue or something separate from the internal library update issue.

- Mac OS X 10.14.6
- Oasys 1.2
- ShadowOui 1.5.91 < 1.5.94

**Comment by lucarebuffi** [comment]
Dear user,

the last version of the pip library is creating a lot of issues. I strongly invite you to install the last binary distribution of the application for MAC. It should be working fine (at least according to my tests).

In case you have again a looping request of update, you can disable the auto-update of the internal libraries in the Preferences (Oasys1->Preferences):

![Screen Shot 2020-10-07 at 2 08 00 PM](https://user-images.githubusercontent.com/6713598/95376493-ca815900-08a6-11eb-9e51-f78815ad0947.png)

Do not hesitate to contact me for any other issues.

**Comment by lucarebuffi** [comment]
Anyway, from the issues you had, I guess that you have another python environment installed on your computer.
Is that true?

**Comment by amicitas** [comment]
The new OASYS binary seems to have solved the issue.

I do have several python environments installed through `macports` and `pyenv`. My current default version when I open a terminal and source my bash startup files is 3.8.6 with up-to-date libraries as of a few days ago..
