### ISSUE TITLE
install fails in Linux if a different miniconda path is given

### ISSUE THREAD

**Issue by marcocamma** [oasys-kit/oasys-installation-scripts#14]
The title says it all
when prompted by the install scripts I have tried to use a different folder for the miniconda folder but the install-scritps :+1: 
```
no change     /home/marco/programs/miniconda3/etc/profile.d/conda.sh
no change     /home/marco/programs/miniconda3/etc/fish/conf.d/conda.fish
no change     /home/marco/programs/miniconda3/shell/condabin/Conda.psm1
no change     /home/marco/programs/miniconda3/shell/condabin/conda-hook.ps1
no change     /home/marco/programs/miniconda3/lib/python3.7/site-packages/xontrib/conda.xsh
no change     /home/marco/programs/miniconda3/etc/profile.d/conda.csh
modified      /home/marco/.bashrc

==> For changes to take effect, close and re-open your current shell. <==

If you'd prefer that conda's base environment not be activated on startup, 
   set the auto_activate_base parameter to false: 

conda config --set auto_activate_base false

Thank you for installing Miniconda3!
Miniconda 3 installed. Installing Oasys
./install_oasys.sh: line 35: cd: /home/marco/miniconda3/bin: No such file or directory
marco@xps:~/oasys-scripts/Linux$ vim install_oasys.sh 
```
It makes sense when looking at the install script but it is confusing since the "miniconda installer" asks where to install miniconda :-)

I am installing using the default one for the moment
Thanks a lot,
marco

**Comment by lucarebuffi** [comment]
Indeed it does. This is my mistake, that option should be avoided and the installation should go in the default directory, at least for now. I made sure that happens in the windows script, but I forgot to do it in the Linux one.

Please reinstall OASYS in the proposed default directory, until I fix the script accordingly.
