### ISSUE TITLE
Could not load the Qt platform plugin "xcb" in "" 

### ISSUE THREAD

**Issue by kdliss** [oasys-kit/oasys-installation-scripts#16]
hello,
trying to install oasys on debian 10. the installer run through.
then starting oasys by:  ~/miniconda3/bin/python -m oasys.canvas

gives the following error:

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted
kdl@whyalla:~$  ~/miniconda3/bin/python -m oasys.canvas
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted

any help? - regards, Klaus

**Comment by lucarebuffi** [comment]
Dear Klaus,

This has nothing to do with OASYS. I don't think the installation went without problems, something wrong happened while installing PyQt and probably the error messages went unnoticed. You can try again and this time try to save the entire output stream on a file (and send it to me). In case we can have a quick zoom call and do it together.

**Comment by SergioLordano** [comment]
Dear all,

we also observed this error in many computers in our institution... luckly it has been always easy to workaround, as below:

sudo apt-get install libxcb-xinerama0

after solving the "xcb" problem, we experienced errors in syned and wofry, but it could then be solved by upgrading these packages. 

Hope it helps... Cheers!

**Comment by lucarebuffi** [comment]
It will help for sure. I will add the suggestion in the instructions, because we can't add sudo operations in the scripts (the should work with user's grant). Thank you very much Sergio!
