### ISSUE TITLE
starting fails with the most recent OasysWriter upgrade

### ISSUE THREAD

**Issue by bdetlefs** [oasys-kit/oasys-installation-scripts#17]
it seems to be related to libwiser (see below). Downgrading libwiser

`pip install libwiser=0.12.2`

seems to solve the problem.

Extract from the error on launching Oasys:
```
    from LibWiser.Foundation import ComputationResults
    File "C:\Users\janousov\AppData\Roaming\Python\Python37\site-packages\LibWiser\Foundation.py", line 1661
    def Source(self):
      ^
    SyntaxError: invalid syntax
```

**Comment by lucarebuffi** [comment]
Dear user, this Add-on is not developed by the OASYS team. Please forward the issue to the authors and in the correct repository:
https://github.com/oasys-elettra-kit/WISEr


In the meantime you can uninstall the broken library:

pip uninstall libwiser
pip uninstall oasys1-wiser
