### ISSUE TITLE
Installation problems oasys1.3 in windows 10

### ISSUE THREAD

**Issue by VictorLijianmin** [oasys-kit/oasys-installation-scripts#18]
Dear developer, 
I have some problems when I install add-ones XOPPY in windows10. Can you help me to solve it? Please

![screenshot](https://user-images.githubusercontent.com/49177381/130817196-f8e9aaa4-34ad-4d8d-85a3-ce5ac216b56d.PNG)
[error code.txt](https://github.com/oasys-kit/oasys-installation-scripts/files/7048068/error.code.txt)

**Comment by VictorLijianmin** [comment]
Collecting OASYS1-XOPPY
  Using cached OASYS1_XOPPY-1.1.1-py3-none-any.whl
Requirement already satisfied: srxraylib>=1.0.30 in c:\users\18316\miniconda3\lib\site-packages (from OASYS1-XOPPY) (1.0.30)
Requirement already satisfied: oasys1>=1.2.62 in c:\users\18316\miniconda3\lib\site-packages (from OASYS1-XOPPY) (1.2.85)
Collecting oasys-srwpy
  Using cached oasys-srwpy-1.0.3.tar.gz (4.3 MB)
Requirement already satisfied: pySRU in c:\users\18316\appdata\roaming\python\python38\site-packages (from OASYS1-XOPPY) (0.5.3)
Requirement already satisfied: requests in c:\users\18316\miniconda3\lib\site-packages (from oasys1>=1.2.62->OASYS1-XOPPY) (2.24.0)
Requirement already satisfied: scipy>=1.4.1 in c:\users\18316\miniconda3\lib\site-packages (from oasys1>=1.2.62->OASYS1-XOPPY) (1.7.1)
Requirement already satisfied: hdf5plugin in c:\users\18316\miniconda3\lib\site-packages (from oasys1>=1.2.62->OASYS1-XOPPY) (3.1.1)
Requirement already satisfied: setuptools in c:\users\18316\miniconda3\lib\site-packages (from oasys1>=1.2.62->OASYS1-XOPPY) (50.3.1.post20201107)
Requirement already satisfied: matplotlib>=3.3.2 in c:\users\18316\miniconda3\lib\site-packages (from oasys1>=1.2.62->OASYS1-XOPPY) (3.4.3)
Requirement already satisfied: wofry>=1.0.25 in c:\users\18316\miniconda3\lib\site-packages (from oasys1>=1.2.62->OASYS1-XOPPY) (1.0.29)
Requirement already satisfied: numpy>=1.18.0 in c:\users\18316\miniconda3\lib\site-packages (from oasys1>=1.2.62->OASYS1-XOPPY) (1.18.5)
Requirement already satisfied: syned>=1.0.20 in c:\users\18316\miniconda3\lib\site-packages (from oasys1>=1.2.62->OASYS1-XOPPY) (1.0.23)
Requirement already satisfied: silx==0.15.0 in c:\users\18316\miniconda3\lib\site-packages (from oasys1>=1.2.62->OASYS1-XOPPY) (0.15.0)
Requirement already satisfied: PyQt5==5.15.2 in c:\users\18316\miniconda3\lib\site-packages (from oasys1>=1.2.62->OASYS1-XOPPY) (5.15.2)
Requirement already satisfied: oasys-canvas-core>=1.0.6 in c:\users\18316\miniconda3\lib\site-packages (from oasys1>=1.2.62->OASYS1-XOPPY) (1.0.6)
Requirement already satisfied: oasys-widget-core>=1.0.1 in c:\users\18316\miniconda3\lib\site-packages (from oasys1>=1.2.62->OASYS1-XOPPY) (1.0.1)
Requirement already satisfied: PyQt5-sip<13,>=12.8 in c:\users\18316\miniconda3\lib\site-packages (from PyQt5==5.15.2->oasys1>=1.2.62->OASYS1-XOPPY) (12.9.0)
Requirement already satisfied: h5py in c:\users\18316\miniconda3\lib\site-packages (from silx==0.15.0->oasys1>=1.2.62->OASYS1-XOPPY) (3.4.0)
Requirement already satisfied: six in c:\users\18316\miniconda3\lib\site-packages (from silx==0.15.0->oasys1>=1.2.62->OASYS1-XOPPY) (1.15.0)
Requirement already satisfied: fabio>=0.9 in c:\users\18316\miniconda3\lib\site-packages (from silx==0.15.0->oasys1>=1.2.62->OASYS1-XOPPY) (0.11.0)
Requirement already satisfied: cycler>=0.10 in c:\users\18316\miniconda3\lib\site-packages (from matplotlib>=3.3.2->oasys1>=1.2.62->OASYS1-XOPPY) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\18316\miniconda3\lib\site-packages (from matplotlib>=3.3.2->oasys1>=1.2.62->OASYS1-XOPPY) (1.3.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\18316\miniconda3\lib\site-packages (from matplotlib>=3.3.2->oasys1>=1.2.62->OASYS1-XOPPY) (2.8.2)
Requirement already satisfied: pillow>=6.2.0 in c:\users\18316\miniconda3\lib\site-packages (from matplotlib>=3.3.2->oasys1>=1.2.62->OASYS1-XOPPY) (8.3.1)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\18316\miniconda3\lib\site-packages (from matplotlib>=3.3.2->oasys1>=1.2.62->OASYS1-XOPPY) (2.4.7)
Requirement already satisfied: idna<3,>=2.5 in c:\users\18316\miniconda3\lib\site-packages (from requests->oasys1>=1.2.62->OASYS1-XOPPY) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\18316\miniconda3\lib\site-packages (from requests->oasys1>=1.2.62->OASYS1-XOPPY) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\18316\miniconda3\lib\site-packages (from requests->oasys1>=1.2.62->OASYS1-XOPPY) (2021.5.30)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\18316\miniconda3\lib\site-packages (from requests->oasys1>=1.2.62->OASYS1-XOPPY) (1.25.11)
Building wheels for collected packages: oasys-srwpy
  Building wheel for oasys-srwpy (setup.py): started
  Building wheel for oasys-srwpy (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\18316\Miniconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\18316\\AppData\\Local\\Temp\\pip-install-tg5gn2wt\\oasys-srwpy_3115e85b9ea74975a24bb382a3b0aebb\\setup.py'"'"'; __file__='"'"'C:\\Users\\18316\\AppData\\Local\\Temp\\pip-install-tg5gn2wt\\oasys-srwpy_3115e85b9ea74975a24bb382a3b0aebb\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\18316\AppData\Local\Temp\pip-wheel-33l5s_ry'
       cwd: C:\Users\18316\AppData\Local\Temp\pip-install-tg5gn2wt\oasys-srwpy_3115e85b9ea74975a24bb382a3b0aebb\
  Complete output (25 lines):
  running bdist_wheel
  running build
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\18316\AppData\Local\Temp\pip-install-tg5gn2wt\oasys-srwpy_3115e85b9ea74975a24bb382a3b0aebb\setup.py", line 87, in <module>
      setup(
    File "C:\Users\18316\Miniconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\18316\Miniconda3\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\18316\Miniconda3\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\18316\Miniconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\18316\Miniconda3\lib\site-packages\wheel\bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "C:\Users\18316\Miniconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\18316\Miniconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\18316\AppData\Local\Temp\pip-install-tg5gn2wt\oasys-srwpy_3115e85b9ea74975a24bb382a3b0aebb\setup.py", line 70, in run
      check_dependencies()
    File "C:\Users\18316\AppData\Local\Temp\pip-install-tg5gn2wt\oasys-srwpy_3115e85b9ea74975a24bb382a3b0aebb\setup.py", line 60, in check_dependencies
      raise Exception("You need to install the SDK Windows 8.1 with Visual Studio Utils and set msbuild.exe path in global environment")
  Exception: You need to install the SDK Windows 8.1 with Visual Studio Utils and set msbuild.exe path in global environment
  ----------------------------------------
  ERROR: Failed building wheel for oasys-srwpy
  Running setup.py clean for oasys-srwpy
Failed to build oasys-srwpy
Installing collected packages: oasys-srwpy, OASYS1-XOPPY
    Running setup.py install for oasys-srwpy: started
    Running setup.py install for oasys-srwpy: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\18316\Miniconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\18316\\AppData\\Local\\Temp\\pip-install-tg5gn2wt\\oasys-srwpy_3115e85b9ea74975a24bb382a3b0aebb\\setup.py'"'"'; __file__='"'"'C:\\Users\\18316\\AppData\\Local\\Temp\\pip-install-tg5gn2wt\\oasys-srwpy_3115e85b9ea74975a24bb382a3b0aebb\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\18316\AppData\Local\Temp\pip-record-vxcv8ncy\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\18316\AppData\Roaming\Python\Python38\Include\oasys-srwpy'
         cwd: C:\Users\18316\AppData\Local\Temp\pip-install-tg5gn2wt\oasys-srwpy_3115e85b9ea74975a24bb382a3b0aebb\
    Complete output (27 lines):
    running install
    running build
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\18316\AppData\Local\Temp\pip-install-tg5gn2wt\oasys-srwpy_3115e85b9ea74975a24bb382a3b0aebb\setup.py", line 87, in <module>
        setup(
      File "C:\Users\18316\Miniconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\18316\Miniconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\18316\Miniconda3\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\18316\Miniconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\18316\Miniconda3\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\18316\Miniconda3\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Users\18316\Miniconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\18316\Miniconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\18316\AppData\Local\Temp\pip-install-tg5gn2wt\oasys-srwpy_3115e85b9ea74975a24bb382a3b0aebb\setup.py", line 70, in run
        check_dependencies()
      File "C:\Users\18316\AppData\Local\Temp\pip-install-tg5gn2wt\oasys-srwpy_3115e85b9ea74975a24bb382a3b0aebb\setup.py", line 60, in check_dependencies
        raise Exception("You need to install the SDK Windows 8.1 with Visual Studio Utils and set msbuild.exe path in global environment")
    Exception: You need to install the SDK Windows 8.1 with Visual Studio Utils and set msbuild.exe path in global environment
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\18316\Miniconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\18316\\AppData\\Local\\Temp\\pip-install-tg5gn2wt\\oasys-srwpy_3115e85b9ea74975a24bb382a3b0aebb\\setup.py'"'"'; __file__='"'"'C:\\Users\\18316\\AppData\\Local\\Temp\\pip-install-tg5gn2wt\\oasys-srwpy_3115e85b9ea74975a24bb382a3b0aebb\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\18316\AppData\Local\Temp\pip-record-vxcv8ncy\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\18316\AppData\Roaming\Python\Python38\Include\oasys-srwpy' Check the logs for full command output.

**Comment by lucarebuffi** [comment]
I am sorry about the inconvenient, but OASYS 1.3 has not been released yet. **_Please install OASYS 1.2._**

I seriously doubt you will be able to compile SRW without the exact version of VC++ installed in your system (it should be VC 14.2). Please follow the instructions here:

https://github.com/oasys-kit/oasys-installation-scripts/wiki/Install-Oasys-in-Windows-10

The installation script will download and install a SPECIFIC version of Miniconda, for which we precompiled SRW (and Shadow) and distributed a wheel file.

**Comment by lucarebuffi** [comment]
I also modified the 1.3 installation script to warn the user about it before installing it.

**Comment by VictorLijianmin** [comment]
thank you so much！nice day！
