### ISSUE TITLE
Windows installer does not support white spaces in the path name

### ISSUE THREAD

**Issue by capitanevs** [oasys-kit/oasys-installation-scripts#22]
Not a big deal, but the (Windows) installer scripts generates error here
![immagine](https://user-images.githubusercontent.com/13431660/164245073-f7b74136-6521-4bb6-82a7-0d2270b05327.png)

if `%cd%` contains blank spaces.

I tried to wrap with "..." but it seemed not working.
Perhaps just a disclaimer about avoiding blanks in the path is enough.

Hope it helps,

M

**Comment by lucarebuffi** [comment]
The workaround is to create a variable where to store the path in dos format. I am fixing all the impacted scripts.

**Comment by lucarebuffi** [comment]
The issue should be resolved with the last release of the installation scripts
