### ISSUE TITLE
orangecontrib not found after installing Oasys on Ubuntu

### ISSUE THREAD

**Issue by cuncta** [oasys-kit/oasys-installation-scripts#23]
I followed thei Installation instructions for Linux [here](https://github.com/oasys-kit/oasys-installation-scripts/wiki/Install-Oasys-in-Linux),  then I also installed the recommended add-ons. I downloaded the [ShadowOui tutorial](https://github.com/oasys-kit/ShadowOui-Tutorial), and I can not run most of the examples. For instance when I try to run _ex12_bendingmagnet.ows_ I get the following errors
 `
UnknownWidgetDefinition('orangecontrib.shadow.widgets.sources.ow_bending_magnet.BendingMagnet')
UnknownWidgetDefinition('orangecontrib.shadow.widgets.plots.ow_histogram.Histogram')
UnknownWidgetDefinition('orangecontrib.shadow.widgets.plots.ow_histogram.Histogram')
UnknownWidgetDefinition('orangecontrib.shadow.widgets.plots.ow_histogram.Histogram')
UnknownWidgetDefinition('orangecontrib.shadow.widgets.plots.ow_plot_xy.PlotXY')
UnknownWidgetDefinition('orangecontrib.shadow.widgets.plots.ow_histogram.Histogram')`

In general, from the GUI, when I select any of the Shadow widgets, none is present. I use Ubuntu 18.04.

**Comment by srio** [comment]
It looks that the ShadowOui add-on is not installed or its installation failed. 

- Please check in the Options->Add-ns that ShadowOui is installed. If so, you may try to uninstall and then re-install it.
- If error persists, would you please send the terminal log when  you launch Oasys? For that you can start oasys from a terminal by doing:
```
~/miniconda3/bin/python -m oasys.canvas -l4 --force-discovery
```

**Comment by cuncta** [comment]
I tried to reinstall ShadowOUI, did not work. 


This is the output:

[oasys_log.txt](https://github.com/oasys-kit/oasys-installation-scripts/files/9028474/oasys_log.txt)

**Comment by srio** [comment]
The problem is that for whatever reason the xraylib package is not installed.
 
Try this from a terminal:
```
~/miniconda3/bin/conda install -c conda-forge xraylib=3.3.0
```

**Comment by cuncta** [comment]
@srio I guess it was not only my problem, I just helped out a colleague that uses mint that had the exact same issue.
