### ISSUE TITLE
add `mv ~/miniconda3/lib/libcrypto.so.1.1 ~/miniconda3/lib/__libcrypto.so.1.1` to Known Issue fix

### ISSUE THREAD

**Issue by userbeats** [oasys-kit/oasys-installation-scripts#25]
In [Known Issues](https://github.com/oasys-kit/oasys-installation-scripts/wiki/Install-Oasys-in-Linux#3-known-issues):

`    from PyQt5.QtNetwork import (
ImportError: /lib64/libk5crypto.so.3: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b`

solved by:
`mv ~/miniconda3/lib/libcrypto.so.1.1 ~/miniconda3/lib/__libcrypto.so.1.1`

**Comment by lucarebuffi** [comment]
My mistake. Fixed, thanks!
