### ISSUE TITLE
Errors: "Orangecontrib" and "DepreciationWarning"

### ISSUE THREAD

**Issue by chuixiaopaopao** [oasys-kit/oasys-installation-scripts#26]
Hello, 

1. When installing, there was an error:
**ModuleNotFoundError: No module named 'orangecontrib'**
2. After installation, when running OASYS, there was a warning:
DepreciationWarning. 

Please see the attached screenshots.

Thanks,
April
![Oasys installation error screenshot](https://github.com/oasys-kit/oasys-installation-scripts/assets/143754540/0cc2a072-e0b4-40bf-a43c-3e9f8cc6c605)
![Oasys installation error screenshot3](https://github.com/oasys-kit/oasys-installation-scripts/assets/143754540/30c187b2-9fb5-4928-bc26-cb59b920b102)

**Comment by lucarebuffi** [comment]
you're fine

**Comment by chuixiaopaopao** [comment]
Ok thanks.
