### ISSUE TITLE
Problem of step-by-step in Windows of OASYS

### ISSUE THREAD

**Issue by oohlala1516** [oasys-kit/oasys-installation-scripts#27]
Dear Sir,
I account a problem when I try to install OASYS. On the third step, after I entered"python -m oasys.canvas -14", nothing happened (I waited for a long time). I'm wondering if you could help me with that problem.

Best regards
Y.HY

**Comment by srio** [comment]
Which platform are you using? Did you get any message? Did you try to double-click on the desktop Oasys icon?

**Comment by oohlala1516** [comment]
Im using Win10 21H2（19044.3086）Professional. No message yet. I double-clicked on the desktop Oasys icon but I only get this
![6f429844ad6d4c6cc479a01ba921b53](https://github.com/oasys-kit/oasys-installation-scripts/assets/94880239/467df87a-841f-4e87-9cd1-10947f669cf5)



> Which platform are you using? Did you get any message? Did you try to double-click on the desktop Oasys icon?

**Comment by srio** [comment]
1) Check you have the c::\<your user>\Miniconda3

2) Open a cmd window and enter
Miniconda3\Scripts\activate

which python 
> you should get something like  /c/Users/srio/Miniconda3/python

python -m oasys.canvas

**Comment by oohlala1516** [comment]
I followed your words but that's that happend next and it hasn' change yet.
![ae36a687d27b891b9868d40cfc56e66](https://github.com/oasys-kit/oasys-installation-scripts/assets/94880239/9ba605f3-ac31-438b-852f-db244777ed60)

**Comment by oohlala1516** [comment]
The OASYS appeared after I waited for about 10 mins. But the cmd window showed a warning.
![Uploading fd80e0eca36865c7cacdfc35684775b.jpg…]()
 Is that going to be a problem?

**Comment by oohlala1516** [comment]
The OASYS appeared after I waited for about 10 mins. But the cmd window showed a warning.
![fd80e0eca36865c7cacdfc35684775b](https://github.com/oasys-kit/oasys-installation-scripts/assets/94880239/e0a97a7c-776b-49b5-9c51-f77cab5abfa9)

Is that going to be a problem?

**Comment by srio** [comment]
This is a warning, it is not the reason of the problem. 
After the 10 min you get the Window? Then if you quit and relauch it does it take so longtime?
In some cases I noticed that the first time Oasys is launched takes quite a long time (< 1min) but never so long, and next times is quicker. 
Try launching oasys with these flags to get a verbose output:
```python -m oasys.canvas -l4 --force-discovery```
Otherwise I confess I cant help more...
