### ISSUE TITLE
ShadowLib could not be initializated

### ISSUE THREAD

**Issue by armagedson** [oasys-kit/oasys-installation-scripts#5]
It is a very attractive software for the X-ray simulation. While it is failed to lunch the software after the Shadow Add-On installed, which followed the instruction on this project Wiki page. The error messages as bellow, please kindly help me on this. The OS is Ubuntu 16.04.

Activating configuration for <class 'oasys.canvas.conf.oasysconf'>
Setting up Canvas main window.
'CanvasScene(objectName='', ...)' intitialized.
Setting registry 'None on 'CanvasScene(objectName='', ...)'.
'CanvasScene(objectName='', ...)' cleared.
'CanvasScene(objectName='', ...)' intitialized.
Setting registry 'None on 'CanvasScene(objectName='', ...)'.
Setting scheme '<oasys.canvas.widgetsscheme.OASYSWidgetsScheme object at 0x7fae94d314c8>' on 'CanvasScene(objectName='', ...)'
Stack transition start ()
Stack transition finished ()
Dock transition finished (new width 640)
Dock transition started.
Time from last update 23:09:37.247611 (1520585415.375638)
Got pypi packages: [Installable(name='OASYS1-ALS-ShadowOui', version='0.0.5', summary='WIDGETS DEVELOPED FOR ALS TO EXTEND SHADOWOUI FUNCTIONALITIES', description='WIDGETS DEVELOPED FOR ALS TO EXTEND SHADOWOUI FUNCTIONALITIES', package_url='http://pypi.python.org/pypi/OASYS1-ALS-ShadowOui', release_urls=[ReleaseUrl(filename='OASYS1-ALS-ShadowOui-0.0.5.tar.gz', url='https://pypi.python.org/packages/b6/5d/67a6954f9cd7170914215dc6b6c3cec116b6d10208283db4b7f46a68ee51/OASYS1-ALS-ShadowOui-0.0.5.tar.gz', size=201628, python_version='source', package_type='sdist')]), Installable(name='OASYS1-WISE', version='1.1.3', summary='WISE in Python', description='WISE in OASYS - Prototype Version', package_url='http://pypi.python.org/pypi/OASYS1-WISE', release_urls=[ReleaseUrl(filename='OASYS1-WISE-1.1.3.tar.gz', url='https://pypi.python.org/packages/e9/21/2f24a6b0ac202cf539fc3d3d48d4de642095a3c6b12e55e2310d1b04c6ed/OASYS1-WISE-1.1.3.tar.gz', size=294050, python_version='source', package_type='sdist')]), Installable(name='OASYS1-XRayServer', version='1.0.19', summary="X-Ray Server: Sergey Stepanov's X-Ray Server on OASYS", description="This is the project for XRayServer (Sergey Stepanov's X-Ray Server) under OASYS", package_url='http://pypi.python.org/pypi/OASYS1-XRayServer', release_urls=[ReleaseUrl(filename='OASYS1-XRayServer-1.0.19.tar.gz', url='https://pypi.python.org/packages/be/c8/9461785c402ac3026d63ce20799508313e352c9610b6692671007550adfa/OASYS1-XRayServer-1.0.19.tar.gz', size=108780, python_version='source', package_type='sdist')]), Installable(name='OASYS1-XOPPY', version='1.0.33', summary='XOPPY: XOP (X-ray oriented programs) in Python', description='This is the project for XOPPY (XOP under python3) under OASYS', package_url='http://pypi.python.org/pypi/OASYS1-XOPPY', release_urls=[ReleaseUrl(filename='OASYS1-XOPPY-1.0.33.tar.gz', url='https://pypi.python.org/packages/11/e8/469486ba8f708566fca7ab7be2119d23be57896ed0bfc9d3e954ff2f2fe0/OASYS1-XOPPY-1.0.33.tar.gz', size=10393642, python_version='source', package_type='sdist')]), Installable(name='OASYS1-ShadowOui', version='1.4.39', summary='Shadow, Ray-tracing simulation software', description='ShadowOui (Shadow3 Oasys User Interface) is an Oasys add-on package to be installed via the add-on manager tool.\n\nIt contains the Shadow 3 ray-tracing simulation software integrated into the Oasys environment.', package_url='http://pypi.python.org/pypi/OASYS1-ShadowOui', release_urls=[ReleaseUrl(filename='OASYS1-ShadowOui-1.4.39.tar.gz', url='https://pypi.python.org/packages/b9/f8/d957876ec2daff4a444e7f8988fa06c35c29c1ed129e662b89eb7de64577/OASYS1-ShadowOui-1.4.39.tar.gz', size=3054738, python_version='source', package_type='sdist')])]
Traceback (most recent call last):
  File "/home/miniconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/miniconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/miniconda3/lib/python3.6/site-packages/oasys/canvas/__main__.py", line 470, in <module>
    sys.exit(main())
  File "/home/miniconda3/lib/python3.6/site-packages/oasys/canvas/__main__.py", line 432, in main
    raise e
  File "/home/miniconda3/lib/python3.6/site-packages/oasys/canvas/__main__.py", line 271, in main
    menu_registry = conf.menu_registry()
  File "/home/miniconda3/lib/python3.6/site-packages/oasys/canvas/conf.py", line 115, in menu_registry
    return discovery.MenuRegistry(list(omenus()))
  File "/home/miniconda3/lib/python3.6/site-packages/oasys/canvas/conf.py", line 108, in omenus
    yield from discovery.omenus_from_package(menu)
  File "/home/miniconda3/lib/python3.6/site-packages/oasys/canvas/discovery.py", line 36, in omenus_from_package
    menu_module = discovery.asmodule(name)
  File "/home/miniconda3/lib/python3.6/site-packages/orangecanvas/registry/discovery.py", line 505, in asmodule
    return __import__(module, fromlist=[""])
  File "/home/miniconda3/lib/python3.6/site-packages/orangecontrib/shadow/menu/ow_shadow_tools_menu.py", line 11, in <module>
    import orangecontrib.shadow.widgets.preprocessor.xsh_bragg as xsh_bragg
  File "/home/miniconda3/lib/python3.6/site-packages/orangecontrib/shadow/widgets/preprocessor/xsh_bragg.py", line 6, in <module>
    from Shadow.ShadowPreprocessorsXraylib import bragg
  File "/home/miniconda3/lib/python3.6/site-packages/Shadow/__init__.py", line 8, in <module>
    from Shadow.ShadowLibExtensions import OE, Source, Beam, CompoundOE 
  File "/home/miniconda3/lib/python3.6/site-packages/Shadow/ShadowLibExtensions.py", line 11, in <module>
    import Shadow.ShadowLib as ShadowLib
SystemError: initialization of ShadowLib raised unreported exception

**Comment by srio** [comment]
Hello,
we had recently some issues with shadow3 that are not yet very clean and reproducible. 

You can try two things: 
1) Uninstall shadow3 (pip uninstall Shadow) and reinstall from sources (https://github.com/srio/shadow3)
2)  download the whl file from:
http://ftp.esrf.eu/pub/scisoft/shadow3/wheels/
and then
pip install shadow3-18.1.24-cp36-cp36m-linux_x86_64.whl

I would start by solution 2) as it was successful for other people (see full discussion in https://github.com/lucarebuffi/ShadowOui/issues/187)
