### ISSUE TITLE
Installation problems after OASYS1-SRW==1.0.52 (GLIBC_2.27) on Ubuntu 16

### ISSUE THREAD

**Issue by SergioLordano** [oasys-kit/oasys-installation-scripts#6]
Hi all, I am just writing after a lot of trouble with the latest release of OASYS1-SRW. It happened in more than one computer, so we thought it could be helpful to someone else.   

After upgrading to OASYS1-SRW==1.0.52, this weird bug started appearing, making it impossible to import srwlib in the miniconda environment:
```
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /home/miniconda3/lib/python3.7/site-packages/srwlpy.so)
```
I tried to solve this several ways, but was not successful. Maybe this could be due to srwlpy.so being compiled in a newer version of Ubuntu, as pointed by @arturcpinto, but this is just a guess. The only way we found to work this out was installing on a fresh Ubuntu 18 LTS. Both ShadowOui and SRW are working fine, but still there were a few problems which I leave documented here:

After following the instructions on this page and installing OASYS via miniconda, the following error arised when I ran `./start_oasys_MC.sh`:
```
ImportError: numpy.core.multiarray failed to import
```
This is due to a double installation of numpy, by both conda and pip. The solution was to uninstall all of them and install numpy by conda, only. The problem with this is that it automatically uninstalled `xraylib` and ShadowOui wouldn't load. Simply running `conda install -c conda-forge xraylib` did the thing work again. 

This is just a note, in case it happens with other people. Hope it is useful =]

**Comment by lucarebuffi** [comment]
It is useful, indeed. Thanks for publishing this note.

The new version of SRW libraries has been compiled with Ubuntu 18.04 LTS, recently downloaded. I compiled them for both miniconda and python.org distributions. Probably something changed in the meantime, since the default python 3 installed does not show some compatibility issues we found in the past, asking us to use miniconda3.

I suggest to remove the folder miniconda3 and install from scratch Oasys by using the VirtualEnvironment scripts, that let you use the Python.org python.

**Comment by wcgrizolli** [comment]
@SergioLordano said:

> The solution was to uninstall all of them and install numpy by conda, only.

I noted something that may be related to the same problem. The line:

https://github.com/oasys-kit/oasys-installation-scripts/blob/dabda10ffc17c61e25738bdb12ab8a428e6c53aa/Release_1.1/Miniconda/install_oasys1_MC.sh#L35

would better be

`$HOME/miniconda3/bin/conda install numpy=XXX`

where XXX is the desired version for numpy.

This may solve the conflicts of different versions of numpy.

**Comment by lucarebuffi** [comment]
I will do it. Anyway, there is not a desired version of numpy. It should be the last. I repeat: use the virtual environment with standard python.org python!

**Comment by lucarebuffi** [comment]
Fixed

**Comment by SergioLordano** [comment]
Hello Luca, 
I am sorry to bother you again about this, but there is also a small problem with the Virtual Environment installation. It can be easily fixed, but beginners may spend a lot of time on it. When we call the script start_oasys_VE.sh, it starts OASYS but does not load ShadowOui widgets, because it fails to import xraylib. If you look the code:

```
#!/bin/bash
source ~/oasys1env/bin/activate
#source `find /home -name "start_oasys.sh" -printf "%h"`/oasys1env/bin/activate
export LD_LIBRARY_PATH=/home/oasys/oasys1env/lib/xraylib 
export DYLD_LIBRARY_PATH=/home/oasys1env/lib/xraylib
python -m oasys.canvas -l4 --force-discovery
```

it is easy to see why it does not find xraylib library: in many computers, the home path is not simply `/home`. So It could be fixed by using:
```
export LD_LIBRARY_PATH=~/oasys1env/lib/xraylib 
export DYLD_LIBRARY_PATH=~/oasys1env/lib/xraylib
```

**Comment by lucarebuffi** [comment]
That was just a (outrageous) BUG. Thank you for your precious feedback!
