### ISSUE TITLE
Error install windows 10

### ISSUE THREAD

**Issue by Angelrf86** [oasys-kit/oasys-installation-scripts#8]
I have a problem while running 

python -m oasys.canvas -l4 --force-discovery

See below:

Traceback (most recent call last):
  File "C:\Programfiles\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Programfiles\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Programfiles\Anaconda3\lib\site-packages\oasys\canvas\__main__.py", line 470, in <module>
    sys.exit(main())
  File "C:\Programfiles\Anaconda3\lib\site-packages\oasys\canvas\__main__.py", line 432, in main
    raise e
  File "C:\Programfiles\Anaconda3\lib\site-packages\oasys\canvas\__main__.py", line 256, in main
    canvas_window = OASYSMainWindow()
  File "C:\Programfiles\Anaconda3\lib\site-packages\oasys\canvas\mainwindow.py", line 412, in __init__
    lastdelta = datetime.now() - datetime.fromtimestamp(timestamp)
OSError: [Errno 22] Invalid argument

**Comment by lucarebuffi** [comment]
try remove --force-discovery

**Comment by lucarebuffi** [comment]
I will dig into it asap.

**Comment by Angelrf86** [comment]
Thank you, Luca,

try 1st shame output.

**Comment by lucarebuffi** [comment]
It's very perplexing. datetime is a python basic library, a wrong argument error means that it has been changed somehow recently and made incompatible with the previous version. That's upsetting....My colleague at the APS uses the Windows version, I will use his environment as a test asap

**Comment by lucarebuffi** [comment]
I can't reproduce the error. Have you tried to remove all the options? 

python -m oasys.canvas

In any case, you have no reason to launch Oasys with the additional options unless you are developing code.

**Comment by Angelrf86** [comment]
I get the same result as above.

**Comment by srio** [comment]
Hi, 

1) could you give me the result of
python --version

2) open python and enter 
import datetime
import oasys

3) in the installation instructions it is recommended to install miniconda in c:\
you use anaconda in another dir. This may be possible, but I believe you have something not clean in your installation. Try to install miniconda as suggested (no need to uninstall your anaconda)

I hope this helps!

Rgds, M
